mvarandas/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('people.urls', namespace='people')),
]

people/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$', views.People.index, name='index'),
	url(r'^register/', views.People.register, name='register'),
	url(r'^list_registers/', views.People.list_registers, name='list_registers'),
	url(r'^edit_register/(?P<id>\d+)/', views.People.edit_register, name='edit_register'),
	url(r'^remove_register/(?P<id>\d+)/', views.People.remove_register, name='remove_register'),
	url(r'^search_register/', views.People.search_register, name='search_register'),
]

people/models.py
from django.db import models

# Create your models here.

class MPeople(models.Model):

	name = models.CharField(max_length=100, blank=True)
	address = models.CharField(max_length=200)
	city = models.CharField(max_length=100)
	state = models.CharField(max_length=2)
	country = models.CharField(max_length=50)
	cep = models.CharField(max_length=50)
	phone = models.CharField(max_length=13, blank=True)
	gender = models.CharField(max_length=1)
	email = models.EmailField(blank=True)
	birthday = models.DateField(blank=True)
	cpf = models.CharField(max_length=11)

people/forms.py
from django import forms
from .models import MPeople
from django_localflavor_br.forms import BRCPFField, BRPhoneNumberField


class RegisterForm(forms.ModelForm):

	cpf = BRCPFField(widget=forms.TextInput(attrs={'placeholder': 'Only numbers'}))
	phone = BRPhoneNumberField(widget=forms.TextInput(attrs={'placeholder': 'Only numbers'}))	

	class Meta:
		model = MPeople

		widgets = {
			'cep': forms.TextInput(attrs={'placeholder': 'XXXXX-XXX or only numbers'}),
			'gender': forms.TextInput(attrs={'placeholder': 'M for Male and F for Female'}),
			'birthday': forms.DateInput(attrs={'placeholder': 'DD/MM/YYYY', 'format': '%d/%m/%Y'}),
		}
		
		birthday = forms.DateField()

		fields = ('name', 'address', 'city', 'state', 'country', 'cep', 'phone', 'gender', 'email', 'birthday', 'cpf')


class SearchForm(forms.ModelForm):

	phone = BRPhoneNumberField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Only numbers'}))
	name = forms.CharField(required=False)


	class Meta:
		model = MPeople

		fields = ('name', 'phone')


class FilterForm(forms.ModelForm):
	'''Filtrate with optional parameters: age, gender or city'''

	def __init__(self, *args, **kwargs):
		super(FilterForm, self).__init__(*args, **kwargs)

		database = MPeople.objects.all()

		age_choices = database.values('birthday').distinct()
		iage_choices = [('', 'None')] + [(id, id) for id in age_choices]
		self.fields['birthday'] = forms.ChoiceField(choices=iage_choices, widget=forms.Select(), required=False, localize=True)

		gender_choices = database.values_list('gender', flat=True).distinct()
		igender_choices = [('', 'None')] + [(id, id) for id in gender_choices]
		self.fields['gender'] = forms.ChoiceField(choices=igender_choices, widget=forms.Select(), required=False)

		city_choices = database.values_list('city', flat=True).distinct()
		icity_choices = [('', 'None')] + [(id, id) for id in city_choices]
		self.fields['city'] = forms.ChoiceField(choices=icity_choices, widget=forms.Select(), required=False)

	class Meta:
		model = MPeople

		fields = ('birthday', 'gender', 'city')

people/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, SearchForm, FilterForm
from .models import MPeople
from django.shortcuts import get_object_or_404
import re

# Create your views here.

class People(object):

	def index(request):
		return render(request, 'index.html')


	def register(request):
		if request.method == 'POST':
			form = RegisterForm(request.POST)

			if form.is_valid():
				user = form.save()
				user.save()
				return redirect('/register/')

		else:
			form = RegisterForm()

		return render(request, 'register.html', {'register_form': form})


	def list_registers(request):
		registers = MPeople.objects.all()
		
		if request.method == 'POST':
			form = FilterForm(request.POST or None)

			if form.is_valid():

				context = {
					'age': request.POST['age'],
					'gender': request.POST['gender'],
					'city': request.POST['city'],
				}

				if context['age']:
					age_choosed = re.sub("[''{ birthday: datetime.date()}]", '', context['age'])
					age_choosed = re.sub('[,]', '-', age_choosed)

					registers = MPeople.objects.filter(birthday=age_choosed)

				elif context['city']:
					registers = MPeople.objects.filter(city=form.cleaned_data.get('city'))

				elif request.POST['gender']:
					registers = MPeople.objects.filter(gender=form.cleaned_data.get('gender'))

		else:
			form = FilterForm()

		return render(request, 'list.html', {'registers': registers, 'form_filter': form})


	def edit_register(request, id):
		user_id = MPeople.objects.filter(id=id)

		form_user = get_object_or_404(MPeople, id=user_id)
		
		if request.method == 'POST':
			form = RegisterForm(request.POST, instance=form_user)

			if form.is_valid():
				user = form.save()
				user.save()
				return redirect('/list_registers/')

		else:
			form = RegisterForm(instance=form_user)

		return render(request, 'edit_register.html', {'form_edit_register': form})


	def remove_register(request, id):
		user_id = get_object_or_404(MPeople, id=id)
		user_id.delete()

		return redirect('/list_registers/')

	def search_register(request):

		search = None

		if request.method == 'GET':
			form_search = SearchForm(request.GET)

			if form_search.is_valid():

				field_content = {
					'name': form_search.cleaned_data.get('name'),
					'phone': form_search.cleaned_data.get('phone'),
					}

				if field_content['name'] != "" and field_content['phone'] != "":
					search = MPeople.objects.filter(name=field_content['name'], phone=field_content['phone'])

				elif field_content['name'] != "":
					search = MPeople.objects.filter(name=field_content['name'])

				elif field_content['phone'] != "":
					search = MPeople.objects.filter(phone=field_content['phone'])


		else:
			form_search = SearchForm()

		return render(request, 'search_register.html', {'form': form_search, 'search': search})

people/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<title>
		{% block title %}
		{% endblock %}
	</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/milligram/1.3.0/milligram.min.css" integrity="sha256-Ro/wP8uUi8LR71kwIdilf78atpu8bTEwrK5ZotZo+Zc=" crossorigin="anonymous" />
	<!--<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
	<link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">
	<link rel="stylesheet" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">-->
</head>
<body>
	{% block body %}
	{% endblock %}
</body>
</html>

people/templates/edit_register.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Edit Register{% endblock %}

{% block body %}

<div class="container" style="width: 500px;">
	<h2 align="center">Register</h2>
	
	{% for field in form_edit_register %}
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
					<label for="field.id_for_label">{{field.label}}</label>
						{{field|add_class:'form-control'}}
				
				{% for error in field.errors %}
					<span class="help-block">{{error}}</span>
				{% endfor %}
	{% endfor %}
		<div class="submit" align="center">
			<button type="submit" class="button">Send</button>
		</div>
	</form>

	<div class="return" align="center">
		<a class="button button-outline" href="{% url 'people:list_registers' %}">Return</a>
	</div>
</div>

{% endblock %}

people/templates/index.html
{% extends 'base.html' %}

{% block title %}Menu{% endblock %}

{% block body %}

<style type="text/css">
	.button{
		width: 250px;
	}
</style>

<div class="container" align="center">
	<h1>Menu</h1>

	<a class="button" href="{% url 'people:register' %}">Register</a><br>
	<a class="button" href="{% url 'people:search_register' %}">Search</a><br>
	<a class="button" href="{% url 'people:list_registers' %}">List of Registers</a>

</div>

{% endblock %}

people/templates/list.html
{% extends 'base.html' %}

{% block title %}List of Registers{% endblock %}

{% block body %}

<div class="container">
	<h1 align="center">Registers</h1>

	<form method="post" action="." enctype="multipart/form-data">
		{% csrf_token %}

		{{form_filter.as_p}}

		<button type="submit" class="button">Filtrate</button>
		
	</form>
	
	{% if form_filter %}
		<table class="informations">
			<thead>
				<tr>
					<th>Name</th>
					<th>Address</th>
					<th>City</th>
					<th>State</th>
					<th>Country</th>
					<th>CEP</th>
					<th>Phone</th>
					<th>Gender</th>
					<th>Email</th>
					<th>Birthday</th>
					<th>CPF</th>
				</tr>
			</thead>
			{% for user in registers %}
			<tbody>
				<tr>
					<td>{{user.name}}</td>
					<td>{{user.address}}</td>
					<td>{{user.city}}</td>
					<td>{{user.state}}</td>
					<td>{{user.country}}</td>
					<td>{{user.cep}}</td>
					<td>{{user.phone}}</td>
					<td>{{user.gender}}</td>
					<td>{{user.email}}</td>
					<td>{{user.birthday}}</td>
					<td>{{user.cpf}}</td>
					<td><a class="button" href="{% url 'people:edit_register' id=user.id %}">Change</a></td>
					<td><a class="button" href="{% url 'people:remove_register' id=user.id %}">Remove</a></td>
				</tr>
			</tbody>
			{% endfor %}

		</table>

	{% else %}

		<table class="filtrated_informations">
			<thead>
				<tr>
					<th>Name</th>
					<th>Address</th>
					<th>City</th>
					<th>State</th>
					<th>Country</th>
					<th>CEP</th>
					<th>Phone</th>
					<th>Gender</th>
					<th>Email</th>
					<th>Birthday</th>
					<th>CPF</th>
				</tr>
			</thead>
			{% for user in filtred_registers %}
			<tbody>
				<tr>
					<td>{{user.name}}</td>
					<td>{{user.address}}</td>
					<td>{{user.city}}</td>
					<td>{{user.state}}</td>
					<td>{{user.country}}</td>
					<td>{{user.cep}}</td>
					<td>{{user.phone}}</td>
					<td>{{user.gender}}</td>
					<td>{{user.email}}</td>
					<td>{{user.birthday}}</td>
					<td>{{user.cpf}}</td>
					<td><a class="button" href="{% url 'people:edit_register' id=user.id %}">Change</a></td>
					<td><a class="button" href="{% url 'people:remove_register' id=user.id %}">Remove</a></td>
				</tr>
			</tbody>
			{% endfor %}

		</table>
		
	{% endif %}
	<div class="return" align="center">
		<a class="button button-outline" href="/">Return</a>
	</div>
</div>

{% endblock %}

people/templates/register.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Registration{% endblock %}

{% block body %}

<div class="container" style="width: 500px;">
	<h2 align="center">Register</h2>
	
	{% for field in register_form %}
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
					<label for="field.id_for_label">{{field.label}}</label>
						{{field|add_class:'form-control'}}
				
				{% for error in field.errors %}
					<span class="help-block">{{error}}</span>
				{% endfor %}
	{% endfor %}

		<div class="submit" align="center">
			<button type="submit" class="button">Send</button>
		</div>

	</form>

	<div class="return" align="center">
		<a class="button button-outline" href="{% url 'people:index' %}">Return</a>
	</div>
</div>

{% endblock %}

people/templates/search_register.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Search{% endblock %}

{% block body %}

<div class="container" style="width: 500px;">

	<h2 align="center">Search</h2>
	
	{% for field in form %}
		<form method="get" enctype="multipart/form-data">
			{% csrf_token %}
					<label for="field.id_for_label">{{field.label}}</label>
						{{field|add_class:'form-control'}}
				
				{% for error in field.errors %}
					<span class="help-block">{{error}}</span>
				{% endfor %}
	{% endfor %}

		<div class="submit" align="center">
			<button type="submit" class="button">Send</button>	
		</div>

	</form>

	{% if search %}
		<table>
			<thead>
				<tr>
					<th>Name</th>
					<th>Address</th>
					<th>Phone</th>
				</tr>
			</thead>
		
		{% for result in search %}
			<tbody>
				<tr>
					<td>{{result.name}}</td>
					<td>{{result.address}}</td>
					<td>{{result.phone}}</td>
				</tr>
			</tbody>

		{% endfor %}

		</table>
	{% else %}
		<h3 align="center">Not Found</h3>

	{% endif %}

	<div class="return" align="center">
		<a class="button button-outline" href="{% url 'people:index' %}">Return</a>
	</div>
</div>

{% endblock %}